kind: Deployment
apiVersion: apps/v1
metadata:
  name: finalproject
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finalproject
  template:
    metadata:
      labels:
        app: finalproject
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 50m  ## 5% of the 1 core cpu on the vm
